---
- hosts: webserver

  tasks:

  - name: deploy master branch
    git:
      repo: https://github.com/JohanLi/johanli.com.git
      dest: /var/www/{{ domain }}
      force: yes

  - name: deploy static files
    synchronize:
      src: ../../build/
      dest: /var/www/{{ domain }}/build/

  - name: npm install
    command: npm install --production chdir=/var/www/{{ domain }}

  - name: restart application
    systemd:
      state: restarted
      daemon_reload: yes
      name: "{{ domain }}.service"
