---
- hosts: mysql

  tasks:

  - name: install mysql-server
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - mysql-server
      - python-mysqldb

  - name: delete anonymous users
    mysql_user:
      name: ""
      state: absent

  - name: remove test database
    mysql_db:
      db: test
      state: absent

  - name: add user for remote access, and set password for all users
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      priv: "*.*:ALL,GRANT"
      host: "{{ item }}"
    loop:
      - "{{ home_ip }}"
      - "{{ domain }}"
      - 127.0.0.1
      - ::1
      - localhost

  # https://github.com/mysqljs/mysql/issues/1507
  - name: set user plugin to mysql_native_password
    command: mysql -e "UPDATE mysql.user SET plugin = 'mysql_native_password'"

  - name: add .my.cnf with new credentials
    template:
      src: ../templates/.my.cnf
      dest: ~/.my.cnf
      owner: root
      group: root
      mode: 0600

  - name: overwrite bind-address to allow remote access
    blockinfile:
      path: /etc/mysql/my.cnf
      block: |
        [mysqld]
        bind-address=*

  - name: restart mysql
    service:
      name: mysql
      enabled: yes
      state: restarted
