---
- hosts: webservers

  tasks:

  - name: deploy master branch
    git: repo=https://github.com/JohanLi/johanli.com.git dest=/var/www/{{ domain }}

  - name: start node application
    command: "{{ item }} chdir=/var/www/{{ domain }}"
    environment:
      NODE_ENV: production
    with_items:
    - npm install
    - gulp
    - forever restart app.js