---
- hosts: webservers

  tasks:

  - name: deploy master branch
    git: repo=https://github.com/JohanLi/johanli.com.git dest=/var/www/{{ domain }}

  - name: deploy images
    copy: src=../public/img/ dest=/var/www/{{ domain }}/public/img/

  - name: start application
    command: "{{ item }} chdir=/var/www/{{ domain }}"
    with_items:
    - npm install
    - npm run build
    - npm run production:start